# NumPy

## Example from documentation

In [46]:
# The standard way to import NumPy:
import numpy as np

# Create a 2-D array, set every second element in
# some rows and find max per row:

x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
x
# array([[  0,   1,   2,   3,   4],
#        [-99,   6, -99,   8, -99],
#        [-99,  11, -99,  13, -99]])

x.max(axis=1)
# array([ 4,  8, 13])

array([ 4,  8, 13])

In [47]:
# Generate normally distributed random numbers:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
len(samples)

2500

## Examples from Course

In [1]:
import numpy as np

In [2]:
l = [1,2,3]

In [3]:
type(l)

list

In [6]:
arr = np.array(l)

In [7]:
type(l)

list

In [8]:
type(arr)

numpy.ndarray

In [14]:
l = [[1,2,3],[4,5,6]]

In [15]:
m = np.array(l)

In [16]:
# 2-dim array
m

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
m.shape

(2, 3)

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.zeros((2,3)) + 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [51]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.linspace(1,10,10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
np.eye(2)

array([[1., 0., 0., 1.]])

## Rand Numbers

In [105]:
rng = np.random.default_rng(42)
rng.uniform(size=(2,2))

array([[0.77395605, 0.43887844],
       [0.85859792, 0.69736803]])

In [109]:
rng = np.random.default_rng(42)
rng.standard_normal((2,2))

array([[ 0.30471708, -1.03998411],
       [ 0.7504512 ,  0.94056472]])

In [110]:
rng = np.random.default_rng(42)
rng.normal(10,2,(2,2))

array([[10.60943416,  7.92003179],
       [11.50090239, 11.88112943]])

In [150]:
rng.integers(1,11)

4

In [151]:
arr = np.arange(25)

In [152]:
rarr = rng.integers(0,50,10)

In [155]:
arr.shape

(25,)

In [156]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [162]:
rarr

array([ 3, 48, 22, 44, 33, 38, 37,  9, 18, 23])

In [160]:
rarr.min()

3

In [161]:
rarr.argmin()

0

In [164]:
rarr.dtype

dtype('int64')

## Indexing and Selection

In [192]:
arr = rng.integers(1,11,10)

In [169]:
arr

array([ 5,  4, 10,  4,  1,  5,  8,  2,  5,  2])

In [170]:
arr[0]

5

In [171]:
arr[1:5:]

array([ 4, 10,  4,  1])

In [172]:
arr[::-1]

array([ 2,  5,  2,  8,  5,  1,  4, 10,  4,  5])

In [175]:
(arr+10)/2**2

array([3.75, 3.5 , 5.  , 3.5 , 2.75, 3.75, 4.5 , 3.  , 3.75, 3.  ])

In [181]:
arr

array([ 5,  4, 10,  4,  1,  5,  8,  2,  5,  2])

In [182]:
s = arr[0:5:]

In [183]:
s[::] = 99

In [184]:
s

array([99, 99, 99, 99, 99])

In [185]:
arr

array([99, 99, 99, 99, 99,  5,  8,  2,  5,  2])

In [197]:
arr = arr.reshape(2,5)

In [198]:
arr

array([[ 7,  5,  4,  3,  6],
       [ 7, 10,  5,  2,  9]])

In [204]:
arr[1::,1::]

array([[10,  5,  2,  9]])

In [205]:
arr = rng.integers(1,11,10)
arr

array([7, 8, 1, 4, 8, 9, 5, 9, 9, 4])

In [207]:
b_arr = arr > 4

In [208]:
arr[b_arr]

array([7, 8, 8, 9, 5, 9, 9])

## NumPy Operations